package com.sz.gym.dao;

import com.sz.gym.model.entity.Earning;
import com.sz.gym.model.entity.EarningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface EarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int countByExample(EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int deleteByExample(EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int deleteByPrimaryKey(Integer earningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int insert(Earning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int insertSelective(Earning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    List<Earning> selectByExample(EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    Earning selectByPrimaryKey(Integer earningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") Earning record, @Param("example") EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int updateByExample(@Param("record") Earning record, @Param("example") EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int updateByPrimaryKeySelective(Earning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    int updateByPrimaryKey(Earning record);
}