package com.sz.gym.model.entity;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_description
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String activityDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_user
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String activityUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_residueTime
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Integer activityResiduetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.update_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_status
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String activityStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_description
     *
     * @return the value of activity.activity_description
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getActivityDescription() {
        return activityDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_description
     *
     * @param activityDescription the value for activity.activity_description
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription == null ? null : activityDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_user
     *
     * @return the value of activity.activity_user
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getActivityUser() {
        return activityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_user
     *
     * @param activityUser the value for activity.activity_user
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setActivityUser(String activityUser) {
        this.activityUser = activityUser == null ? null : activityUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_residueTime
     *
     * @return the value of activity.activity_residueTime
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Integer getActivityResiduetime() {
        return activityResiduetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_residueTime
     *
     * @param activityResiduetime the value for activity.activity_residueTime
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setActivityResiduetime(Integer activityResiduetime) {
        this.activityResiduetime = activityResiduetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_time
     *
     * @return the value of activity.create_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_time
     *
     * @param createTime the value for activity.create_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.update_time
     *
     * @return the value of activity.update_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.update_time
     *
     * @param updateTime the value for activity.update_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_status
     *
     * @return the value of activity.activity_status
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_status
     *
     * @param activityStatus the value for activity.activity_status
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setActivityStatus(String activityStatus) {
        this.activityStatus = activityStatus == null ? null : activityStatus.trim();
    }
}