package com.sz.gym.model.entity;

import java.util.Date;

public class Facilities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.id
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.facilities_name
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private String facilitiesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.number
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.create_time
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.update_time
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.discription
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private String discription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.facilities_Status
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    private String facilitiesStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.id
     *
     * @return the value of facilities.id
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.id
     *
     * @param id the value for facilities.id
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.facilities_name
     *
     * @return the value of facilities.facilities_name
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public String getFacilitiesName() {
        return facilitiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.facilities_name
     *
     * @param facilitiesName the value for facilities.facilities_name
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setFacilitiesName(String facilitiesName) {
        this.facilitiesName = facilitiesName == null ? null : facilitiesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.number
     *
     * @return the value of facilities.number
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.number
     *
     * @param number the value for facilities.number
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.create_time
     *
     * @return the value of facilities.create_time
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.create_time
     *
     * @param createTime the value for facilities.create_time
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.update_time
     *
     * @return the value of facilities.update_time
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.update_time
     *
     * @param updateTime the value for facilities.update_time
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.discription
     *
     * @return the value of facilities.discription
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.discription
     *
     * @param discription the value for facilities.discription
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.facilities_Status
     *
     * @return the value of facilities.facilities_Status
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public String getFacilitiesStatus() {
        return facilitiesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.facilities_Status
     *
     * @param facilitiesStatus the value for facilities.facilities_Status
     *
     * @mbggenerated Thu Mar 12 10:23:03 CST 2020
     */
    public void setFacilitiesStatus(String facilitiesStatus) {
        this.facilitiesStatus = facilitiesStatus == null ? null : facilitiesStatus.trim();
    }
}