package com.sz.gym.model.entity;

public class FileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.file_id
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.file_name
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.file_address
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    private String fileAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.file_description
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    private String fileDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.file_id
     *
     * @return the value of fileinfo.file_id
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.file_id
     *
     * @param fileId the value for fileinfo.file_id
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.file_name
     *
     * @return the value of fileinfo.file_name
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.file_name
     *
     * @param fileName the value for fileinfo.file_name
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.file_address
     *
     * @return the value of fileinfo.file_address
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public String getFileAddress() {
        return fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.file_address
     *
     * @param fileAddress the value for fileinfo.file_address
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress == null ? null : fileAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.file_description
     *
     * @return the value of fileinfo.file_description
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.file_description
     *
     * @param fileDescription the value for fileinfo.file_description
     *
     * @mbggenerated Wed Mar 18 09:45:36 CST 2020
     */
    public void setFileDescription(String fileDescription) {
        this.fileDescription = fileDescription == null ? null : fileDescription.trim();
    }
}