package com.sz.gym.model.entity;

import java.util.Date;

public class Finance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.finance_id
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Integer financeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.finance_name
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String financeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.finance_description
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String financeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.finance_type
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private String financeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.create_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.money
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_id
     *
     * @return the value of finance.finance_id
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Integer getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.finance_id
     *
     * @param financeId the value for finance.finance_id
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setFinanceId(Integer financeId) {
        this.financeId = financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_name
     *
     * @return the value of finance.finance_name
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getFinanceName() {
        return financeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.finance_name
     *
     * @param financeName the value for finance.finance_name
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setFinanceName(String financeName) {
        this.financeName = financeName == null ? null : financeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_description
     *
     * @return the value of finance.finance_description
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getFinanceDescription() {
        return financeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.finance_description
     *
     * @param financeDescription the value for finance.finance_description
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setFinanceDescription(String financeDescription) {
        this.financeDescription = financeDescription == null ? null : financeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_type
     *
     * @return the value of finance.finance_type
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public String getFinanceType() {
        return financeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.finance_type
     *
     * @param financeType the value for finance.finance_type
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setFinanceType(String financeType) {
        this.financeType = financeType == null ? null : financeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.create_time
     *
     * @return the value of finance.create_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.create_time
     *
     * @param createTime the value for finance.create_time
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.money
     *
     * @return the value of finance.money
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.money
     *
     * @param money the value for finance.money
     *
     * @mbggenerated Fri Mar 13 17:04:02 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}